language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer self-update
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/
  - ./vendor/bin/phpcs --standard=PSR2 ./test/

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
